version: '3.7'

services:
  homewizard_report:
    image: electronick/homewizard_monthly_report:latest
    container_name: homewizard_report
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped