version: '3.7'

services:
  homewizard_report:
    image: tonnomutilisateur/homewizard_monthly_report:latest
    container_name: homewizard_report
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped